### ISSUE TITLE
Nothing happens...

### ISSUE THREAD

**Issue by sgrayban** [jneilliii/Octoprint-STLViewer#36] opened 2021-02-24 12:54 UTC
I pick the file and render type and nothing shows up -- just a purple image area.

**Comment by jneilliii** [comment] 2021-02-24 14:36
can you share a screenshot? Are there any errors in the browser's developer console (f12 on your keyboard typically) on the console tab? and finally, you are actually selecting stl files not gcode files?

**Comment by sgrayban** [comment] 2021-02-24 23:20
Many errors in the console but I dont know which ones pertain to your plugin...

![image](https://user-images.githubusercontent.com/1351910/109079484-d930a700-76b3-11eb-9a0a-a01087f0f247.png)

**Comment by jneilliii** [comment] 2021-02-25 00:34
Thanks for the screenshot, can you provide a list of installed plugins?

**Comment by jneilliii** [comment] 2021-02-25 00:37
Just to make sure, I installed this plugin fresh just now and uploaded an stl file and it's working for me.

![image](https://user-images.githubusercontent.com/5249455/109085482-c0d28380-76d7-11eb-8e3e-b7cd208fabe7.png)

**Comment by sgrayban** [comment] 2021-02-25 01:14
The plugins....

```
Name	Actions
Access Anywhere - The Spaghetti Detective (1.5.3)
 Homepage  TSD Team
Monitor and control your printer anywhere over the internet, on your phone! No port-forwarding or VPN is needed. Best part? AI-based failure detection!
 AGPLv3  Python >=2.7,<4  
 |  | 
Action Command Notification Support  
 Gina Häußge
Allows your printer to trigger notifications via action commands on the connection
 AGPLv3  Python >=2.7,<4  
 |  | 
Action Command Prompt Support  
 Gina Häußge
Allows your printer to trigger prompts via action commands on the connection
 AGPLv3  Python >=2.7,<4  
 |  | 
Announcement Plugin  
 Gina Häußge
Announcements all around OctoPrint
 AGPLv3  Python >=2.7,<4  
 |  | 
Anonymous Usage Tracking  
 Homepage  Gina Häußge
Anonymous version and usage tracking, see homepage for details on what gets tracked
 AGPLv3  Python >=2.7,<4  
 |  | 
Application Keys Plugin  
 Gina Häußge, Aldo Hoeben
Implements a workflow for third party clients to obtain API keys
 AGPLv3  Python >=2.7,<4  
 |  | 
Backup & Restore  
 Gina Häußge
Backup & restore your OctoPrint settings and data
 AGPLv3  Python >=2.7,<4  
 |  | 
Backup Scheduler (0.0.4)
 Homepage  jneilliii
Schedule OctoPrint backups at regular intervals.
 MIT  Python >=2.7,<4  
 |  | 
Core Wizard  
 Gina Häußge
Provides wizard dialogs for core components and functionality
 AGPLv3  Python >=2.7,<4  
 |  | 
Creality-2x-temperature-reporting-fix (0.0.4)
 Homepage  SimplyPrint & Brad Morgan
Fixes the temperature reporting from Creality printers shipped with the new mainboard (new Ender-3 Pro's, Ender-3 Pro v2, CR-6 SE & possibly more)
 MIT  Python >=2.7,<4  
 |  | 
Dashboard (1.17.0)
 Homepage  j7126
A dashboard tab for Octoprint that displays the most relevant info regarding the state of the printer and any on-going print jobs.
 AGPLv3  Python >=2.7,<4  
 |  | 
Detailed Progress (0.2.7)
 Homepage  Tom M
Displays detailed progress on the LCD screen
 AGPLv3  Python >=2.7,<4  
 |  | 
Discovery  
 Homepage  Gina Häußge
Makes the OctoPrint instance discoverable via Bonjour/Avahi/Zeroconf and uPnP
 AGPLv3  Python >=2.7,<4  
 |  | 
DisplayLayerProgress Plugin (1.25.4)
 Homepage  Olli
Displays the current processing layer and the percentage in Printer Display and in Desktop
 AGPLv3  Python >=2.7,<4  
 |  | 
Error Tracking  
 Gina Häußge
 AGPLv3  Python >=2.7,<4  
 |  | 
File Check (2021.2.23) 
 Homepage  Gina Häußge
Checks for common issues in uploaded files
 AGPLv3  Python >2.7,<4  
 |  | 
Firmware Check (2021.2.4) 
 Homepage  Gina Häußge
Checks for unsafe or broken printer firmwares
 AGPLv3  Python >=2.7,<4  
 |  | 
Fullscreen Plugin (0.0.6)
 Homepage  Paul de Vries
Open webcam in fullscreen mode
 AGPLv3  Python >=2.7,<4  
 |  | 
GCode Viewer  
 Gina Häußge
Provides a GCODE viewer in OctoPrint's UI.
 AGPLv3  Python >=2.7,<4  
 |  | 
GcodeEditor (0.2.12)
 Homepage  ieatacid
Edit gcode from OctoPrint
 AGPLv3  Python >=2.7,<4  
 |  | 
Logging  
 Shawn Bruce, based on work by Gina Häußge and Marc Hannappel
Provides access to OctoPrint's logs and logging configuration.
 AGPLv3  Python >=2.7,<4  
 |  | 
MQTT (0.8.7)
 Homepage  Gina Häußge
An OctoPrint Plugin that adds support for MQTT to OctoPrint.
 AGPLv3  Python >=2.7,<4  
 |  | 
Navbar Temperature Plugin (0.14)
 Homepage  Jarek Szczepanski & Cosik
Displays temperatures on navbar
 AGPLv3  Python >=2.7,<4  
 |  | 
OctoEverywhere! (0.6.3)
 Homepage  Quinn Damerell
Access OctoPrint remotely over the internet anywhere! Including full webcam streaming. Free. Simple. Secure.
 AGPLv3  Python >=2.7,<4  
 |  | 
OctoPrint-WideScreen (0.1.4)
 Homepage  jneilliii
Plugin that adds a right sidebar panel and moves specified panels from left sidebar to the right sidebar.
 AGPLv3  Python >=2.7,<4  
 |  | 
OctoPrint-WiFiStatus (1.5.1)
 Homepage  Manuel McLure
Displays WiFi status on the navbar
 AGPLv3  Python >=3.7,<4  
 |  | 
OctoVox Plugin (0.1.6)
 Homepage  John Ruzick
Query your printer from Amazon Echo without exposing your server and api keys!
 AGPLv3  Python >=2.7,<4  
 |  | 
Pi Support Plugin  
 Gina Häußge
Provides additional information about your Pi in the UI.
 AGPLv3  Python >=2.7,<4  
 |  | 
PrettyGCode (1.2.4)
 Homepage  Kragrathea
Pretty GCode Visualizer
 AGPLv3  Python >=2.7,<4  
 |  | 
Printer Stats (3.1.2)
 Homepage  Alex Verrico
Statistics of your 3D Printer
 AGPLv3  Python >=3.6,<4  
 |  | 
Resource Monitor (0.3.1)
 Homepage  Renaud Gaspard
A plugin to view the current CPU and RAM usage on your system
 MIT  Python >=2.7,<4  
 |  | 
Software Update  
 Homepage  Gina Häußge
Allows receiving update notifications and performing updates of OctoPrint and plugins
 AGPLv3  Python >=2.7,<4  
 |  | 
STL Viewer (0.4.2)
 Homepage  jneilliii
A plugin to load stl files in viewer.
 AGPLv3  Python >=2.7,<4  
 |  | 
Tab Order (0.5.12)
 Homepage  jneilliii
Simple plugin to allow reordering of tabs within OctoPrint.
 AGPLv3  Python >=2.7,<4  
 |  | 
Terminal Messaging (0.1.0)
 Homepage  jeffeb3
Adds styling to the terminal tab that makes it easier to see where a message is from.
 MIT  Python >=2.7,<4  
 |  | 
Themeify (1.2.2)
 Homepage  Birk Johansson
Beautiful themes for octoprint
 AGPLv3  Python >=2.7,<4  
 |  | 
Virtual Printer  
 Gina Häußge, based on work by Daid Braam
Provides a virtual printer via a virtual serial port for development and testing purposes
 AGPLv3  Python >=2.7,<4
```

**Comment by jneilliii** [comment] 2021-02-28 20:26
Can you test these demos and let me know if they load? This is the underlying library I'm using to render the stl files. If these don't work for you then there's not going to be much I can do to resolve this.

http://www.knowhave.com/jsc3d/demos/

**Comment by sgrayban** [comment] 2021-02-28 22:12
Yup those all worked

**Comment by tibmeister** [comment] 2021-05-10 20:38
Only works if the file is uploaded via the web GUI.  I save to the watched folder then let Octoprint process them, and these do not show up.  This is a non-starter for me.

**Comment by jneilliii** [comment] 2021-05-10 20:50
adding them to octoprint via the watched folder should have no effect on how the plugin sees the stl files @tibmeister. The plugin links to the file list on the left hand side of the UI, so if you don't see files in the drop-down do you see `STL` files in the file list?

**Comment by tibmeister** [comment] 2021-05-12 17:59
Yes, the files show up, I select them to load or print, and everything's good.  In the STL viewer, or even the slicer plugin, if I save to the watched folder, nothing in the dropdown, if I upload then I can see the file.  I also can confirm that only files uploaded through the GUI are visible, as I had several files already in the file list from the watched folder and I uploaded a new one through the GUI and only could see the one uploaded through the GUI.

**Comment by jneilliii** [comment] 2021-05-12 19:52
sounds like something isn't working right for your watched folder. Anything that goes through the watched folder should be visible within the file list, and therefore accessible by the plugin. If that is not the case, then you may have found a bug with core OctoPrint, in which case you should open an issue on its repository with full logs, etc. I'll see if I can get around to testing this myself later tonight if I can.

**Comment by jneilliii** [comment] 2021-05-13 00:08
@tibmeister just finished testing and am unable to reproduce your issue as described. I upload to the watched folder, it automatically gets processed by OctoPrint, shows up in the file list and is available to select for the STL Viewer.

https://user-images.githubusercontent.com/5249455/118059101-b41c0e00-b35d-11eb-9fd4-61ad178e5abf.mp4

@sgrayban as for the original issue of it not displaying anything, can you please provide an example stl file to test on my end?

**Comment by jneilliii** [comment] 2022-11-10 21:56
Closing due to non-response.

**Closed as completed by jneilliii** 2022-11-10 21:56 UTC
Labels: bug
